#!/bin/bash
set -e

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║                    Solar Monitor Installation Script                       ║
# ║                                                                            ║
# ║ Automates setup of Docker, environment variables, and project startup    ║
# ╚════════════════════════════════════════════════════════════════════════════╝

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_NAME="solar-monitor"
ENV_FILE="$SCRIPT_DIR/.env"
DATA_DIR="$SCRIPT_DIR/data"

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# ─────────────────────────────────────────────────────────────────────────────
# Helper functions
# ─────────────────────────────────────────────────────────────────────────────

print_header() {
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BLUE}${1}${NC}"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}

print_success() {
    echo -e "${GREEN}✓ ${1}${NC}"
}

print_error() {
    echo -e "${RED}✗ ${1}${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ ${1}${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ ${1}${NC}"
}

# ─────────────────────────────────────────────────────────────────────────────
# Check prerequisites
# ─────────────────────────────────────────────────────────────────────────────

check_requirements() {
    print_header "Verificando requisitos previos"
    
    local missing=()
    
    if ! command -v docker &> /dev/null; then
        missing+=("Docker")
        print_error "Docker no instalado"
    else
        print_success "Docker instalado"
    fi
    
    if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
        missing+=("Docker Compose")
        print_error "Docker Compose no instalado"
    else
        print_success "Docker Compose instalado"
    fi
    
    if [ ${#missing[@]} -gt 0 ]; then
        print_header "Instalación de dependencias"
        echo -e "${YELLOW}Por favor instala:${NC}"
        for item in "${missing[@]}"; do
            echo "  • $item"
        done
        echo ""
        echo "Ubuntu/Debian:"
        echo "  curl -fsSL https://get.docker.com | sh"
        echo "  sudo usermod -aG docker \$USER"
        echo ""
        echo "O visita: https://docs.docker.com/get-docker/"
        exit 1
    fi
}

# ─────────────────────────────────────────────────────────────────────────────
# Generate secure passwords
# ─────────────────────────────────────────────────────────────────────────────

generate_password() {
    # Generate a secure random password
    openssl rand -base64 32 | tr -d "=+/" | cut -c1-25
}

# ─────────────────────────────────────────────────────────────────────────────
# Create .env file
# ─────────────────────────────────────────────────────────────────────────────

setup_env() {
    print_header "Configuración de variables de entorno"
    
    if [ -f "$ENV_FILE" ]; then
        print_warning "El archivo .env ya existe"
        read -p "¿Quieres regenerarlo? (s/n): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Ss]$ ]]; then
            print_info "Usando .env existente"
            return
        fi
    fi
    
    print_info "Generando variables de entorno..."
    
    local influx_user="influx_admin"
    local influx_pass=$(generate_password)
    local influx_token=$(generate_password)
    local influx_org="solar"
    local influx_bucket="inverters"
    local poll_interval="60"
    local dashboard_port="80"
    
    cat > "$ENV_FILE" << EOF
# ╔════════════════════════════════════════════════════════════════════════════╗
# ║                    Solar Monitor Configuration                             ║
# ║                                                                            ║
# ║ Generated by install.sh - $(date)                      ║
# ╚════════════════════════════════════════════════════════════════════════════╝

# ─────── InfluxDB ──────────────────────────────────────────────────────────
INFLUXDB_USER=${influx_user}
INFLUXDB_PASSWORD=${influx_pass}
INFLUXDB_TOKEN=${influx_token}
INFLUXDB_ORG=${influx_org}
INFLUXDB_BUCKET=${influx_bucket}

# ─────── Polling ───────────────────────────────────────────────────────────
# Interval en segundos entre lecturas de inversores (rango: 10-3600)
POLL_INTERVAL=${poll_interval}

# ─────── Dashboard ─────────────────────────────────────────────────────────
DASHBOARD_PORT=${dashboard_port}

# ─────── Notas ─────────────────────────────────────────────────────────────
# • Modifica POLL_INTERVAL según necesidad (más bajo = más actualizaciones)
# • DASHBOARD_PORT es el puerto HTTP del dashboard (por defecto 80)
# • InfluxDB UI estará disponible en: http://localhost:8086
# • API docs estará disponible en: http://localhost/api/docs
EOF

    print_success ".env creado con configuración segura"
    print_info "Contraseña de InfluxDB: ${YELLOW}${influx_pass}${NC}"
    print_info "Token de InfluxDB: ${YELLOW}${influx_token:0:20}...${NC}"
}

# ─────────────────────────────────────────────────────────────────────────────
# Create data directory
# ─────────────────────────────────────────────────────────────────────────────

setup_data_dir() {
    print_header "Preparación de directorios"
    
    if [ ! -d "$DATA_DIR" ]; then
        mkdir -p "$DATA_DIR"
        print_success "Directorio de datos creado: $DATA_DIR"
    else
        print_info "Directorio de datos ya existe"
    fi
}

# ─────────────────────────────────────────────────────────────────────────────
# Start services
# ─────────────────────────────────────────────────────────────────────────────

start_services() {
    print_header "Iniciando servicios"
    
    cd "$SCRIPT_DIR"
    
    print_info "Descargando imágenes Docker (esto puede tardar 1-2 minutos)..."
    docker-compose pull
    
    print_info "Iniciando contenedores..."
    docker-compose up -d
    
    # Wait for services to be ready
    print_info "Esperando a que los servicios estén listos..."
    sleep 10
    
    if docker-compose ps | grep -q "Up"; then
        print_success "Servicios iniciados"
    else
        print_error "Algunos servicios no se iniciaron correctamente"
        print_info "Verifica los logs con: docker-compose logs"
        exit 1
    fi
}

# ─────────────────────────────────────────────────────────────────────────────
# Verify installation
# ─────────────────────────────────────────────────────────────────────────────

verify_installation() {
    print_header "Verificación de instalación"
    
    local dashboard_port=$(grep "DASHBOARD_PORT" "$ENV_FILE" | cut -d= -f2)
    local failed=0
    
    # Check API
    if curl -s http://localhost:$(( dashboard_port )).api/health > /dev/null 2>&1 || \
       curl -s http://localhost:8000/api/health > /dev/null 2>&1; then
        print_success "API disponible"
    else
        print_warning "API no disponible aún (puede tardar un momento más)"
    fi
    
    # Check InfluxDB
    if curl -s http://localhost:8086/health > /dev/null 2>&1; then
        print_success "InfluxDB disponible"
    else
        print_warning "InfluxDB no disponible aún"
    fi
    
    # Check dashboard
    if curl -s http://localhost:${dashboard_port:-80}/ > /dev/null 2>&1; then
        print_success "Dashboard disponible"
    else
        print_warning "Dashboard no disponible aún (puede tardar)"
    fi
}

# ─────────────────────────────────────────────────────────────────────────────
# Show next steps
# ─────────────────────────────────────────────────────────────────────────────

show_next_steps() {
    local dashboard_port=$(grep "DASHBOARD_PORT" "$ENV_FILE" | cut -d= -f2 || echo "80")
    
    print_header "✓ Instalación completada"
    
    echo ""
    echo -e "${GREEN}Servicios disponibles:${NC}"
    echo -e "  • ${BLUE}Dashboard${NC}:       http://localhost:${dashboard_port:-80}"
    echo -e "  • ${BLUE}API docs${NC}:        http://localhost:${dashboard_port:-80}/api/docs"
    echo -e "  • ${BLUE}InfluxDB UI${NC}:     http://localhost:8086"
    echo ""
    
    echo -e "${GREEN}Credenciales de InfluxDB:${NC}"
    local influx_user=$(grep "INFLUXDB_USER" "$ENV_FILE" | cut -d= -f2)
    local influx_pass=$(grep "INFLUXDB_PASSWORD" "$ENV_FILE" | cut -d= -f2)
    echo -e "  • Usuario: ${YELLOW}${influx_user}${NC}"
    echo -e "  • Contraseña: ${YELLOW}${influx_pass}${NC}"
    echo ""
    
    echo -e "${GREEN}Primeros pasos:${NC}"
    echo "  1. Abre el dashboard: http://localhost:${dashboard_port:-80}"
    echo "  2. Pulsa '+ Añadir inversor'"
    echo "  3. Completa con datos de tu data logger Solarman"
    echo "  4. ¡Listo! Los datos se actualizarán cada 60 segundos"
    echo ""
    
    echo -e "${GREEN}Comandos útiles:${NC}"
    echo "  Ver logs:           docker-compose logs -f"
    echo "  Ver logs de API:    docker-compose logs -f api"
    echo "  Parar servicios:    docker-compose down"
    echo "  Reiniciar:          docker-compose restart"
    echo ""
    
    echo -e "${YELLOW}⚠ Nota importante:${NC}"
    echo "  El archivo .env contiene credenciales. Guárdalo en lugar seguro."
    echo "  Consulta el README para instrucciones detalladas."
}

# ─────────────────────────────────────────────────────────────────────────────
# Main execution
# ─────────────────────────────────────────────────────────────────────────────

main() {
    clear
    print_header "🌞 Solar Monitor - Instalación Automatizada"
    
    check_requirements
    setup_env
    setup_data_dir
    start_services
    verify_installation
    show_next_steps
    
    echo -e "${GREEN}Instalación finalizada exitosamente ✓${NC}"
}

# Run main function
main
